<?php

/* 

{
  "Pages = [
    }
  ]
} */

    class PageHolders {
        public $Pages;
    }
    class Pages {
        public $Id;
        public $SiteId;
        public $IsDefault;
        public $PageId;
        public $Page;
    }
    class Page {
        public $Id;
        public $Code;
        public $Name;
        public $Neutral; 
        public $NeutralId;
    }
    class Neutral {
        public $Id;
        public $Code;
        public $Name;
        public $Neutral;
        public $NeutralId;
    }
	
    $PageHolders = new PageHolders();
    $PageHolders->Pages = array();

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "notfoundController";
    $Page->PageId = 2;
    $Page->ParentId = null;
    $Page->TemplateUrl = "sites/shared/views/notfound.html";
    $Page->IsDefault = false;
    $Page->IsFallback = true;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = false;
    $Page->Key = "notfound";
    $Page->Authenticate = false;
    $Page->Title = "Introuvable";
    $Page->Url = "fr-CA/introuvable";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "notfoundController";
    $Page->PageId = 2;
    $Page->ParentId = null;
    $Page->TemplateUrl = "sites/shared/views/notfound.html";
    $Page->IsDefault = false;
    $Page->IsFallback = true;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = false;
    $Page->Key = "notfound";
    $Page->Authenticate = false;
    $Page->Title = "Not Found";
    $Page->Url = "en-CA/notfound";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "rxController";
    $Page->PageId = 3;
    $Page->ParentId = null;
    $Page->TemplateUrl = "rx.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx";
    $Page->Authenticate = true;
    $Page->Title = "Ordonnances";
    $Page->Url = "fr-CA/rx";
    $Page->RequireAllPermissions = true;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "rxController";
    $Page->PageId = 3;
    $Page->ParentId = null;
    $Page->TemplateUrl = "rx.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx";
    $Page->Authenticate = true;
    $Page->Title = "Prescriptions";
    $Page->Url = "en-CA/rx";
    $Page->RequireAllPermissions = true;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "rxController";
    $Page->PageId = 3;
    $Page->ParentId = null;
    $Page->TemplateUrl = "rx.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx";
    $Page->Authenticate = true;
    $Page->Title = "Filtres";
    $Page->Url = "fr-CA/rx-inactive";
    $Page->RequireAllPermissions = true;
    $Page->AccessRoles = array();

    $Pages->Page = $Page;
    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "rxController";
    $Page->PageId = 3;
    $Page->ParentId = null;
    $Page->TemplateUrl = "rx.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx";
    $Page->Authenticate = true;
    $Page->Title = "Filters";
    $Page->Url = "en-CA/rx-inactive";
    $Page->RequireAllPermissions = true;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "patientListController";
    $Page->PageId = 4;
    $Page->ParentId = null;
    $Page->TemplateUrl = "sites/shared/views/patient/patient-list.html";
    $Page->IsDefault = true;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = false;
    $Page->Key = "patients";
    $Page->Authenticate = true;
    $Page->Title = "Liste des patients";
    $Page->Url = "fr-CA/patients";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "patientListController";
    $Page->PageId = 4;
    $Page->ParentId = null;
    $Page->TemplateUrl = "sites/shared/views/patient/patient-list.html";
    $Page->IsDefault = true;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = false;
    $Page->Key = "patients";
    $Page->Authenticate = true;
    $Page->Title = "Patients List";
    $Page->Url = "en-CA/patients";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "rxManageController";
    $Page->PageId = 10;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-manage.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/management";
    $Page->Authenticate = true;
    $Page->Title = "Gestion des ordonnances";
    $Page->Url = "fr-CA/rx/gestion";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "rxManageController";
    $Page->PageId = 10;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-manage.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/management";
    $Page->Authenticate = true;
    $Page->Title = "Prescriptions management";
    $Page->Url = "en-CA/rx/manage";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "rxAdHocController";
    $Page->PageId = 11;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-adhoc.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/adhoc";
    $Page->Authenticate = true;
    $Page->Title = "Ordonnance ad hoc";
    $Page->Url = "fr-CA/rx/rx-adhoc";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "rxAdHocController";
    $Page->PageId = 11;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-adhoc.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/adhoc";
    $Page->Authenticate = true;
    $Page->Title = "Ad Hoc Prescription";
    $Page->Url = "en-CA/rx/rx-adhoc";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "rxManageController";
    $Page->PageId = 13;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-manage.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/validate";
    $Page->Authenticate = true;
    $Page->Title = "Valider des ordonnances";
    $Page->Url = "fr-CA/rx/valider";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "rxManageController";
    $Page->PageId = 13;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-manage.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/validate";
    $Page->Authenticate = true;
    $Page->Title = "Prescriptions validation";
    $Page->Url = "en-CA/rx/validate";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "rxListController";
    $Page->PageId = 14;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-manage.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/prepare";
    $Page->Authenticate = true;
    $Page->Title = "Préparer des administrations";
    $Page->Url = "fr-CA/rx/preparer";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "rxListController";
    $Page->PageId = 14;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-manage.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/prepare";
    $Page->Authenticate = true;
    $Page->Title = "Prepare administrations";
    $Page->Url = "en-CA/rx/prepare";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "rxListController";
    $Page->PageId = 15;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-manage.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/cancelPreparation";
    $Page->Authenticate = true;
    $Page->Title = "Annuler des préparations d'administrations";
    $Page->Url = "fr-CA/rx/annuler-preparation";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "rxListController";
    $Page->PageId = 15;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-manage.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/cancelPreparation";
    $Page->Authenticate = true;
    $Page->Title = "Cancel administration preparations";
    $Page->Url = "en-CA/rx/cancel-preparation";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "rxAdministrationController";
    $Page->PageId = 16;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-administration.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/administration";
    $Page->Authenticate = true;
    $Page->Title = "Administer";
    $Page->Url = "fr-CA/rx/administration";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "rxAdministrationController";
    $Page->PageId = 16;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-administration.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/administration";
    $Page->Authenticate = true;
    $Page->Title = "Administrer";
    $Page->Url = "en-CA/rx/administration";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "rxManageController";
    $Page->PageId = 17;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-manage.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/startProcessing";
    $Page->Authenticate = true;
    $Page->Title = "Démarrer des ordonnances";
    $Page->Url = "fr-CA/rx/start-processing";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "rxManageController";
    $Page->PageId = 17;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-manage.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/startProcessing";
    $Page->Authenticate = true;
    $Page->Title = "Start Prescriptions";
    $Page->Url = "en-CA/rx/start-processing";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "rxAdHocController";
    $Page->PageId = 18;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-adhoc.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/startAdHocProcessing";
    $Page->Authenticate = true;
    $Page->Title = "Démarrer des ordonnances ad hoc";
    $Page->Url = "fr-CA/rx/start-processing-adhoc";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "rxAdHocController";
    $Page->PageId = 18;
    $Page->ParentId = 3;
    $Page->TemplateUrl = "rx-adhoc.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/startAdHocProcessing";
    $Page->Authenticate = true;
    $Page->Title = "Start Ad Hoc Prescriptions";
    $Page->Url = "en-CA/rx/start-processing-adhoc";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "rxAdministrationController";
    $Page->PageId = 19;
    $Page->ParentId = 11;
    $Page->TemplateUrl = "rx-administration.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/adhoc/administration";
    $Page->Authenticate = true;
    $Page->Title = "Administer";
    $Page->Url = "fr-CA/rx/rx-adhoc/administration";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "rxAdministrationController";
    $Page->PageId = 19;
    $Page->ParentId = 11;
    $Page->TemplateUrl = "rx-administration.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = true;
    $Page->Key = "rx/adhoc/administration";
    $Page->Authenticate = true;
    $Page->Title = "Administrer";
    $Page->Url = "en-CA/rx/rx-adhoc/administration";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "fr-CA";
    $Page->Controller = "testController";
    $Page->PageId = 99;
    $Page->ParentId = null;
    $Page->TemplateUrl = "sites/shared/views/tests/test-sink.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = false;
    $Page->Key = "tests";
    $Page->Authenticate = false;
    $Page->Title = "Test Sink";
    $Page->Url = "fr-CA/tests";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
    $Pages->Page = $Page;

    $Page = new Page();
    $Page->Culture = "en-CA";
    $Page->Controller = "testController";
    $Page->PageId = 99;
    $Page->ParentId = null;
    $Page->TemplateUrl = "sites/shared/views/tests/test-sink.html";
    $Page->IsDefault = false;
    $Page->IsFallback = false;
    $Page->IsLogin = false;
    $Page->UseSiteRoot = false;
    $Page->Key = "tests";
    $Page->Authenticate = false;
    $Page->Title = "Répertoire de tests";
    $Page->Url = "en-CA/tests";
    $Page->RequireAllPermissions = false;
    $Page->AccessRoles = array();
 
    $PageHolders->Pages = $Pages;

    echo json_encode($PageHolders);
   