'use strict';
angular.module(
    'lgi.infra.web.framework',
    [
        'lgi.infra.web.locations',
        'lgi.infra.web.storage',
        'lgi.infra.web.entrepriseServices',
        'lgi.infra.web.cultures',
        'lgi.infra.web.pages',
        'lgi.infra.web.utils',
        'lgi.infra.web.controls',
        'lgi.infra.web.popup',
        'lgi.infra.web.bootstrap',
        'lgi.infra.web.auth',
        'lgi.infra.web.notifications',
        'lgi.infra.web.date',
        'lgi.infra.web.validation',
        'lgi.infra.web.loading',
        'lgi.infra.web.auditing',
        'ngSanitize'
    ]);